version: '3.3'

services:
        
  nodered:
    image: nodered/node-red:latest
    ports:
        - "1880:1880"
    volumes:
        - nodered-storage:/data
    networks:
      - app_network
    deploy:
      mode: replicated
      replicas: 1

  influxdb:
    image: influxdb:2.6
    # configs:
    #   - source: influxdb-conf
    #     target: /etc/influxdb2/config.yml
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - app_network
    deploy:
      mode: replicated
      replicas: 1

  mosquitto:
    image: eclipse-mosquitto:2.0
    configs:
      - source: mosquitto-conf
        target: /mosquitto/config/mosquitto.conf
      - source: mosquitto-pass
        target: /mosquitto/password.txt
        
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mosquitto-data:/mosquitto/data"
      - "mosquitto-log:/mosquitto/log"
    networks:
      - app_network
    deploy:
      mode: replicated
      replicas: 1

  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - app_network
    deploy:
      mode: replicated
      replicas: 1

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    networks:
      - app_network
    deploy:
      mode: replicated
      replicas: 1
      

networks:
  app_network:
    driver: overlay
    attachable: true

volumes:
  nodered-storage:
  chronograf-storage:
  grafana-provisioning:
  grafana-storage:
  influxdb-storage:
  mosquitto-data:
  mosquitto-log:

configs:
  mosquitto-conf:
    file: ./configs/mosquitto.conf
  influxdb-conf:
    file: ./configs/influxdb/config.yml
  mosquitto-pass:
    file: ./secrets/password.txt
